let expres=require('express')
let cors=require('cors')
let route=require('./routes/prodroutes')
let app=express()
app.use(cors())
app.use(express.json())
app.use(bodyparser.json())
app.use("/img",express.static("upimg"))
app.use(bodyparser.urlencoded({exptended:true}))
app.use(bodyparser.json())
app.use("/",route)
app.listen(5000)